### ISSUE TITLE
homework/inventory_data/products.csv

### ISSUE THREAD

**Issue by aircert** [bonobos/fullstack_homework#4]
When downloaded, inventory.csv and products.csv are not in the proper format to be ingested in a ruby script 

Inventory (needs the spaces between the headers removed): 

product_id, waist, length, style, count
1, 28, 36, jet blues, 75
1, 28, 36, grey dogs, 46
1, 28, 36, stone cutters, 72
1, 28, 36, graham slackers, 5
1, 28, 36, blackjacks, 5
1, 28, 36, jetstrams, 46
...

Products:
"product_id", "product_name", "product_image", "product_description"
"1","washed chinos", "https://bonobos-prod-s3.imgix.net/products/26061/original/PNT_WC_GreyDogs_Slim_hero1.jpg?1476915862=&w=1200&auto=format%2Ccompress&dpr=1&q=75&crop=false&fit=clip&w=900&h=1", "All-purpose, 100% cotton chinos with our signature curved waistband for a better, more natural fit. Available in four fits, a full range of colors, and original contrast pocket liners."
"2","jetsetter jeans", "https://bonobos-prod-s3.imgix.net/products/26709/original/hjh9u9m0441y5qv9qlg6qvy4owanulkj.jpg?1477944668=&auto=format%2Ccompress&dpr=1&q=75&crop=false&fit=clip&w=400&h=1", "Innovative stretch denim for first-class comfort. Designed to be extra soft and resilient, they’re the most comfortable jeans you’ve ever worn."
"3","travel jeans", "https://bonobos-prod-s3.imgix.net/products/971/original/DENIM_TravelJeans_AustinAsphalt_category.jpg?1430943616=&auto=format%2Ccompress&dpr=1&q=75&crop=false&fit=clip&w=400&h=1", "The comfort of stretch in a full range of colors. If you need a break from chinos, or more colorful denim, Travel Jeans are for you."
"4","fireside flannels", "https://bonobos-prod-s3.imgix.net/products/25887/original/t92qwcahevxivaob92jkm4x9pbsw2yz7.jpg?1475020923=&auto=format%2Ccompress&dpr=1&q=75&crop=false&fit=clip&w=400&h=1","Our signature better-fitting chino with warm, toasty flannel on the inside."

Things that worked for me: 
* Removing all quotes
* Remove all commas from product_description

**Comment by richardnuno** [comment]
The goal is to handle this difference in formatting during the import.
